defaults: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: sudokuer
  password:

development:
  <<: *default
  database: sudokuer_development

test: &test
  <<: *default
  database: sudokuer_test

production:
  <<: *default
  database: sudokuer_production
